# Filepaths can take multiple files; delimit them with ';'
# .package files can be specified in any order, but Style Sorter will load them in alphabetical order by filepath, just like TS2.
# .xml files will be loaded in the order given in this file; in any conflict, the last-loaded will prevail.

[BSOK Files]
xml_filepath: L:\Games\Sims 2 Utilities\BodyShop\BsokEditorV2.4\Resources\XML\bsok_05cccasok.xml;resources\xml\bsok_00Maxis.xml
icon_filepath: L:\Redirects\Documents\EA Games\The Sims 2 Ultimate Collection Styles\Downloads\BSOK Products\CCCASOK_Extensions_aqualectrix.package;L:\Redirects\Documents\EA Games\The Sims 2 Ultimate Collection Styles\Downloads\BSOK Products\TheCCCASOK_CAS_Organisation_Kit.package;L:\Redirects\Documents\EA Games\The Sims 2 Ultimate Collection Styles\Downloads\BSOK Products\zzz_CCCASOK_IconReplacements_aqualectrix.package

[Color Files]
xml_filepath: resources\xml\StylishSeasonalSortindexes.xml
color_style: Color Traits
color_order: Alphabetical
palette_style: Color Palette Traits
palette_order: Stylish Seasonal CAS

[Namesync Files]
xml_filepath: resources\xml\Namesync_Sortindexes.xml
combined_style: RYB 12-Color Wheel
combined_order: Rainbow